name: Run Python Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Ajusta según la versión de Python que uses

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MyAdventures/requirements.txt  # Instala dependencias de la carpeta MyAdventures

    - name: Run tests with coverage
      run: |
        pytest --cov=MyAdventures --cov-report=term-missing --cov-report=html  # Ejecuta pruebas con cobertura

    - name: Upload coverage to Codecov (opcional)
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml  # Este paso sube el reporte de cobertura a Codecov si lo necesitas
