name: Run Python Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Asegúrate de usar la versión que desees

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Instala las dependencias de tu proyecto
        pip install coverage  # Instala coverage para la cobertura de código

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover  # Ejecuta las pruebas con cobertura
        coverage report  # Muestra el reporte de cobertura en la terminal
        coverage html  # Genera un reporte HTML de la cobertura

    - name: Upload coverage to Codecov (opcional)
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml  # Asegúrate de generar el archivo coverage.xml si lo subes
